LibraryManegement/Models/AuthorBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LibraryManegement.Models
{
    public class AuthorBook
    {
        [Key]
        public long Id { get; set; }

        [ForeignKey("Book")]
        public long Book_id { get; set; }

        [ForeignKey("Author")]
        public long Author_id { get; set; }

        public virtual Book Book { get; set; }
        public virtual Author Author { get; set; }
    }
}

LibraryManegement/Controllers/AuthorBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryManegement.Models;

namespace LibraryManegement.Controllers
{
    public class AuthorBooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        // GET: AuthorBooks
        public ActionResult Index()
        {
            var authorBooks = db.AuthorBooks.Include(a => a.Author).Include(a => a.Book);
            return View(authorBooks.ToList());
        }

        [Authorize]
        // GET: AuthorBooks/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorBook authorBook = db.AuthorBooks.Find(id);
            if (authorBook == null)
            {
                return HttpNotFound();
            }
            return View(authorBook);
        }

        [Authorize]
        // GET: AuthorBooks/Create
        public ActionResult Create()
        {
            ViewBag.Author_id = new SelectList(db.Authors, "Id", "Author_first_name");
            ViewBag.Book_id = new SelectList(db.Books, "IsBn", "Book_title");
            return View();
        }

        [Authorize]
        // POST: AuthorBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Book_id,Author_id")] AuthorBook authorBook)
        {
            if (ModelState.IsValid)
            {
                db.AuthorBooks.Add(authorBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Author_id = new SelectList(db.Authors, "Id", "Author_first_name", authorBook.Author_id);
            ViewBag.Book_id = new SelectList(db.Books, "IsBn", "Book_title", authorBook.Book_id);
            return View(authorBook);
        }

        [Authorize]
        // GET: AuthorBooks/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorBook authorBook = db.AuthorBooks.Find(id);
            if (authorBook == null)
            {
                return HttpNotFound();
            }
            ViewBag.Author_id = new SelectList(db.Authors, "Id", "Author_first_name", authorBook.Author_id);
            ViewBag.Book_id = new SelectList(db.Books, "IsBn", "Book_title", authorBook.Book_id);
            return View(authorBook);
        }

        [Authorize]
        // POST: AuthorBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Book_id,Author_id")] AuthorBook authorBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authorBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Author_id = new SelectList(db.Authors, "Id", "Author_first_name", authorBook.Author_id);
            ViewBag.Book_id = new SelectList(db.Books, "IsBn", "Book_title", authorBook.Book_id);
            return View(authorBook);
        }

        [Authorize]
        // GET: AuthorBooks/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorBook authorBook = db.AuthorBooks.Find(id);
            if (authorBook == null)
            {
                return HttpNotFound();
            }
            return View(authorBook);
        }

        [Authorize]
        // POST: AuthorBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            AuthorBook authorBook = db.AuthorBooks.Find(id);
            db.AuthorBooks.Remove(authorBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryManegement/Views/AuthorBooks/Create.cshtml
@model LibraryManegement.Models.AuthorBook

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AuthorBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Book_id, "Book_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Book_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Book_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author_id, "Author_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Author_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Author_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryManegement/Views/AuthorBooks/Delete.cshtml
@model LibraryManegement.Models.AuthorBook

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AuthorBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author.Author_first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Author_first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Book.Book_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book.Book_title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryManegement/Views/AuthorBooks/Details.cshtml
@model LibraryManegement.Models.AuthorBook

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <h2>Details</h2>

    <div>
        <h4>AuthorBook</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Author.Author_first_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Author.Author_first_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Book.Book_title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Book.Book_title)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

LibraryManegement/Views/AuthorBooks/Edit.cshtml
@model LibraryManegement.Models.AuthorBook

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div>
        <h2 class="float-left d-block">Edit</h2>
        <a class="btn btn-outline-primary float-right" href="@Url.Action("Index", "AuthorBooks")" role="button">Back to List</a>

    </div>
    <div class="m-5">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>AuthorBook</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Book_id, "Book_id", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Book_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Book_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Author_id, "Author_id", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Author_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Author_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>

   
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryManegement/Views/AuthorBooks/Index.cshtml
@model IEnumerable<LibraryManegement.Models.AuthorBook>



<div class="container">

    <div>
        <h2 class="float-left">Sách của tác giả</h2>
        <a class="btn btn-outline-primary float-right" href="@Url.Action("Create", "AuthorBooks")" role="button">Thêm</a>
    </div>

    <table class=" table table-hover">

        <thead>
            <tr>
                <th>
                    Author
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Book.Book_title)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Author.Author_first_name @item.Author.Author_middle_name  @item.Author.Author_last_name 
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.Book_title)
                    </td>
                    <td>
                        @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Chi Tiết", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>